### ISSUE TITLE
Upload/download - que utiliser?

### ISSUE THREAD

**Issue by underk** [underk/pw_french#1]
Ceci est encore à discuter, upload/download est maintenant dans plusieurs dictionnaires et est reconnu.
Pour l'instant j'ai utilisé téléversement/téléchargement à quelques places(facile à changer).
Le but est de trouver quelque chose de facile à comprendre même pour les débutants.

Quelqu'un a une suggestion ou une opinion?

**Comment by eincande** [comment]
Téléverser  n'est pratiquement pas utilisé en France. Est-ce québecois ? 
En fonction du contexte on utilise plutôt  Déposer un fichier, Envoyer un fichier et surtout...Uploader !
Mais je n'ai vraiment pas d'opinion tranchée ... on peut utiliser téléverser si tu veux

**Comment by underk** [comment]
Oui c'est surtout d'origine Québecoise, on veut toujours trouver/créer un mot français à la place d'utiliser des mots anglais. Mais je préfère upload honnêtement, et si en France ce n'est pas connu alors aussi bien rester avec upload.
Définitivement, déposer/envoyer un fichier est une bonne idée si le contexte le permet.

Afin d'avoir des exemples:
La traduction de "upload field" serait "Champ d'upload" ?
Et pour "Max height for uploaded images", ça sera "Hauteur maximale des images uploadées"?

**Comment by plauclair** [comment]
Dans la dernière version, télécharger/verser a été utilisé. C'est une question d'habitude. ;)
